# Dependencies
markdown:         redcarpet
highlighter:      pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

baseurl:	  /searchable-option-list

pages_list:       [
    {
        title: 'Home',
        link:  'index.html',
        tabId: 'home'
    },
    {
        title: 'Configuration',
        link:  'configuration.html',
        tabId: 'configuration'
    },
    {
        title: 'Examples',
        link:  'examples.html',
        tabId: 'examples'
    },
    {
        title:    'Download @github',
        link:     'https://github.com/pbauerochse/searchable-option-list',
        external: true
    }
]
