# Dependencies
markdown:         redcarpet
highlighter:      pygments

baseurl:	  /searchable-option-list

pages_list:       [
    {
        title: 'Home',
        link:  'index.html',
        tabId: 'home'
    },
    {
        title: 'Configuration',
        link:  'configuration.html',
        tabId: 'configuration'
    },
    {
        title: 'Examples',
        link:  'examples.html',
        tabId: 'examples'
    }
]
